version: 2
jobs:
  build:
    docker:
      - image: flatpak/flatpak-builder:base
     
    working_directory: ~/repo

    steps:
      - checkout
      
      - run:
          name: Install fd.o 1.6 Platform & Sdk for i386 & x86_64
          command: |
              flatpak install flathub org.freedesktop.Sdk/i386/1.6
              flatpak install flathub org.freedesktop.Sdk/x86_64/1.6
              flatpak install flathub org.freedesktop.Platform/i386/1.6
              flatpak install flathub org.freedesktop.Platform/x86_64/1.6
      
      - run:
          name: Setup winepak repo
          command: |
              flatpak remote-add  \
                  --no-gpg-verify \
                  --if-not-exists \
                  winepak         \
                  winepak-repo
      
      - run:
          name: Build org.winepak.Sdk/i386/3.0
          command: |
              flatpak-builder         \
                  --arch=i386         \
                  --ccache            \
                  --force-clean       \
                  --repo=winepak-repo \
                  winepak-build       \
                  org.winepak.Sdk.json

      - run:
          name: Build org.winepak.Sdk/x86_64/3.0
          command: |
              flatpak-builder         \
                  --arch=x86_64       \
                  --ccache            \
                  --force-clean       \
                  --repo=winepak-repo \
                  winepak-build       \
                  org.winepak.Sdk.json

      - run:
          name: Build org.winepak.Platform.Compat32/x86_64/3.0
          command: |
              flatpak build-commit-from                           \
                  --src-ref=runtime/org.winepak.Platform/i386/3.0 \
                  winepak-repo                                    \
                  runtime/org.winepak.Platform.Compat32/x86_64/3.0

      - run:
          name: Build org.winepak.Platform.Wine/i386/3.8-staging
          command: |
              flatpak-builder         \
                  --arch=i386         \
                  --ccache            \
                  --force-clean       \
                  --repo=winepak-repo \
                  winepak-build       \
                  wine/3.8-staging/org.winepak.Platform.Wine.json

      - run:
          name: Build org.winepak.Platform.Wine/x86_64/3.8-staging
          command: |
              flatpak-builder         \
                  --arch=x86_64       \
                  --ccache            \
                  --force-clean       \
                  --repo=winepak-repo \
                  winepak-build       \
                  wine/3.8-staging/org.winepak.Platform.Wine.json

      - run:
          name: Build org.winepak.Platform.Wine.Compat32/x86_64/3.8-staging
          command: |
              flatpak build-commit-from                                        \
                  --src-ref=runtime/org.winepak.Platform.Wine/i386/3.8-staging \
                  winepak-repo                                                 \
                  runtime/org.winepak.Platform.Wine.Compat32/x86_64/3.8-staging
